# Generated by Django 4.2.13 on 2026-06-06 08:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="学校"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="学号"
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(default=80, verbose_name="信用分"),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True, default="", max_length=512, verbose_name="头像URL"
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="个人简介"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "普通用户"), ("admin", "管理员")],
                        default="user",
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_certified",
                    models.BooleanField(default=False, verbose_name="是否校园认证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "market_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="分类名")),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="代码"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="market.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "db_table": "market_category",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message",
                    models.TextField(blank=True, default="", verbose_name="最后消息"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后消息时间"
                    ),
                ),
                (
                    "unread_buyer",
                    models.IntegerField(default=0, verbose_name="买家未读数"),
                ),
                (
                    "unread_seller",
                    models.IntegerField(default=0, verbose_name="卖家未读数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="买家",
                    ),
                ),
            ],
            options={
                "verbose_name": "会话",
                "verbose_name_plural": "会话",
                "db_table": "market_conversation",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="售价"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "全新"),
                            ("like_new", "9成新"),
                            ("good", "8成新"),
                            ("fair", "7成新及以下"),
                        ],
                        default="like_new",
                        max_length=16,
                        verbose_name="成色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("on_sale", "在售"),
                            ("pending_sold", "已订未付"),
                            ("sold", "已售"),
                            ("off_shelf", "已下架"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="所在学校"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览数")),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "audit_remark",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="审核备注"
                    ),
                ),
                (
                    "audited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="售出时间"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="market.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "market_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=512, verbose_name="图片URL")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="market.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "db_table": "market_product_image",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "已申请"),
                            ("confirmed", "已确认"),
                            ("shipping", "待取/待发"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="requested",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[("pickup", "校内自取"), ("express", "快递")],
                        default="pickup",
                        max_length=16,
                        verbose_name="交易方式",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="成交价"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="备注"
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="自取地点"
                    ),
                ),
                (
                    "pickup_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="自取时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="买家",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="market.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "market_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, verbose_name="内容")),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="market.conversation",
                        verbose_name="会话",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送方",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "market_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="market.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "market_favorite",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="market.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="卖家",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve_product", "通过商品"),
                            ("reject_product", "驳回商品"),
                            ("off_shelf_product", "下架商品"),
                            ("handle_report", "处理举报"),
                            ("ban_user", "封禁用户"),
                            ("adjust_credit", "调整信用分"),
                        ],
                        max_length=32,
                        verbose_name="操作",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=32, verbose_name="目标类型"),
                ),
                (
                    "target_id",
                    models.IntegerField(blank=True, null=True, verbose_name="目标ID"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "market_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="星级",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", max_length=300, verbose_name="内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="market.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被评价方",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评价方",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
                "db_table": "market_review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reviewee", "-created_at"], name="idx_mkt_rv_reviewee"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "虚假信息"),
                            ("prohibited", "违禁物品"),
                            ("price", "价格异常"),
                            ("harassment", "骚扰"),
                            ("other", "其他"),
                        ],
                        max_length=16,
                        verbose_name="原因",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=300, verbose_name="详细说明"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("warned", "已警告"),
                            ("removed", "已下架"),
                            ("banned", "已封禁"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="market.product",
                        verbose_name="被举报商品",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报",
                "verbose_name_plural": "举报",
                "db_table": "market_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="idx_mkt_rp_status_ctime"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_mkt_prod_status_ctime"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="idx_mkt_prod_cat_status"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller", "status"], name="idx_mkt_prod_seller_status"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="idx_mkt_ord_buyer_status"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "status"], name="idx_mkt_ord_seller_status"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="idx_mkt_msg_conv_time"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("product", "buyer")},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "sort_order"], name="idx_mkt_cat_parent_sort"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["operator", "-created_at"], name="idx_mkt_aud_operator"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="idx_mkt_user_role_active"
            ),
        ),
    ]
